sidebar:
  README.md
  geometry.md
  finite_element_method.md
  machine_learning.md
  reinforcement_learning.md
plugins:
- jekyll-remote-theme
- jekyll-relative-links
remote_theme: pages-themes/architect@v0.2.0
relative_links:
  enabled: true
  collections: true
